### ISSUE TITLE
youtube?

### ISSUE THREAD

**Issue by Edvinas01** [simonas-dev/light-tube-client#1]
i like to see the tube plz

**Comment by ssankauskas** [comment]
You can see naked tube here
![image](https://user-images.githubusercontent.com/32478822/55231266-be84f780-522a-11e9-8946-4c482e681f45.png)

**Comment by simonas-dev** [comment]
naked tube pics. please be gentle.
![image](https://user-images.githubusercontent.com/3253131/55231342-fc821b80-522a-11e9-96e3-deea7e226481.png)

party tube pics.
![image](https://user-images.githubusercontent.com/3253131/55231329-f429e080-522a-11e9-8e0d-66d958589927.png)

**Comment by Edvinas01** [comment]
thank, watermelon +1

**Comment by simonas-dev** [comment]
@Edvinas01 I hope pics satisfied you.

Can I close the issue?

**Comment by Edvinas01** [comment]
plz ytes
